theme: minima
title: My GitHub Pages Project
description: A project with multiple sections linked in a sidebar.
baseurl: ""
url: "https://laqrag.github.io/ffmtg"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional settings
exclude:
  - README.md
  - index.md

theme: jekyll-theme-minimal
title: Final Fantasy MTG
description: FF MTG Collection