theme: jekyll-theme-minimal
title: Final Fantasy MTG
description: Original scene of FF and MTG collaboration card
baseurl: ""
url: "https://laqrag.github.io/ffmtg"
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Optional settings
exclude:
  - README.md
  - index.md